### ISSUE TITLE
One new paper for "Aspect Sentiment Triplet Extraction (ASTE)"

### ISSUE THREAD

**Issue by wutaiqiang** [IsakZhang/ABSA-Survey#4]
https://arxiv.org/abs/2302.13032    ICASSP2023

TL,DR: introduce syntactic information to generative ABSA frameworks

Maybe u can consider to update the paper list or even add into your paper

Thanks!

**Comment by IsakZhang** [comment]
Thanks, glad to know this work, I suggest you directly create a pull request for this (because we expect this can become a tradition so that the community can build this repo together).

**Comment by wutaiqiang** [comment]
thanks. I have made a pull request
